# Haskell Stack configuration
#
# See https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-12.16
#resolver: lts-12.14
#resolver: lts-11.22
#resolver: lts-9.21

packages:
    - ./.

nix:
    enable: true
    pure: true
    packages: []

flags: {}
extra-package-dbs: []
