# Haskell Stack configuration
#
# See https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-12.13
#resolver: lts-11.22
#resolver: lts-9.21

packages:
    - ./.

nix:
    enable: true
    pure: true
    packages: []
    #shell-file: stack/stack.nix

flags: {}
extra-package-dbs: []
